[package]
name = "object-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynasmrt = "1.2.3"
memmap2 = "0.5.8"
object = { version = "0.30.0", features = ["write"] }
