[package]
name = "bf-singlepass-jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynasm = "1.2.3"
libc = "0.2.135"
